name: Build

on:
  workflow_dispatch:
    inputs:
      binexport_commit:
        description: "BinExport commit hash"
        type: string
        default: "HEAD"
        required: true
      binary_ninja_api_commit:
        description: "Binary Ninja API commit hash"
        type: string
        required: true

jobs:
  build:
    runs-on: macos-14
    name: Build BinExport Binary Ninja plugin
    steps:
      - name: Checkout BinExport
        uses: actions/checkout@v4
        with:
          repository: google/binexport
          ref: ${{ github.event.inputs.binexport_commit }}
      - name: Update BinExportDeps.cmake
        # Current hardcoded hash, fragile
        run: sed -i "" 's/6e2b374dece03f6fb48a1615fa2bfee809ec2157/${{ inputs.binary_ninja_api_commit }}/' cmake/BinExportDeps.cmake
      - name: Checkout Binary Ninja API
        uses: actions/checkout@v4
        with:
          repository: Vector35/binaryninja-api
          ref: ${{ inputs.binary_ninja_api_commit }}
          path: .binaryninja-api
      - name: Run regenerate-api-stubs.sh
        run: ./binaryninja/stubs/regenerate-api-stubs.sh .binaryninja-api
      - name: Build BinExport
        run: |
          mkdir -p build_mac
          cd build_mac
          cmake .. \
              -DCMAKE_BUILD_TYPE=Release \
              "-DCMAKE_INSTALL_PREFIX=${PWD}" \
              -DBINEXPORT_ENABLE_IDAPRO=OFF \
              -DBINEXPORT_ENABLE_BINARYNINJA=ON
          cmake --build . --config Release -- "-j$(sysctl -n hw.logicalcpu)"
          ctest --build-config Release --output-on-failure
          cmake --install . --config Release --strip
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binexport12_binaryninja.dylib
          path: build_mac/binexport-prefix/binexport12_binaryninja.dylib
          if-no-files-found: error
